os:
  - linux
language: java
jdk: oraclejdk11
notifications:
  email: false
before_install: true
install: mvn --quiet --batch-mode dependency:go-offline
before_script: true
script: mvn --batch-mode verify
