language: java
jdk: openjdk11
notifications:
  email: false
before_install: true
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --quiet
before_script: true
script: mvn --batch-mode verify
