version: "{build}"
image: Visual Studio 2017
environment:
  PYTHON: "C:\\Python36-x64"
build_script:
- cmd: >-
    python --version

    %PYTHON%\python.exe --version

    dir "C:\Program Files\Java"

    echo "JAVA_HOME=%JAVA_HOME%"

    set JAVA_HOME=C:\Program Files\Java\jdk1.8.0

    java -version

    mvn --version

    mvn install --quiet --batch-mode
